In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
x = np.array([2,3,5,1,2,4])
print(x)
print('total elements =>',x.size)
print('dimension wise elements =>',x.shape)
print ('dimesion count',x.ndim)


[2 3 5 1 2 4]
total elements => 6
dimension wise elements => (6,)
dimesion count 1


In [4]:
y = np.array([[2,3,5],[3,2,1]])
print(y)
print ('total elements =>',y.size)
print('dimension wise elements =>',y.shape)
print ('dimension count' ,y.ndim)

[[2 3 5]
 [3 2 1]]
total elements => 6
dimension wise elements => (2, 3)
dimension count 2


In [5]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])
print ('dimension wise elements =>' ,z.shape)
print ('dimension count ',z.ndim)

dimension wise elements => (3, 3)
dimension count  2


In [6]:
p = [1,2,3,4,5,6,7,8,9,10]
t = np.array([p,p,p,p,p,p,p,p,p,p])
print (t)
print ('total elements',t)
print ('dimension wise element' ,t.shape)
print('dimension count',t.ndim)


[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
total elements [[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
dimension wise element (10, 10)
dimension count 2


In [7]:
d = np.arange(-10,11,.5)
d.shape


(42,)

In [8]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [9]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [10]:
a = np.linspace(1,1000,10)
a

array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.])

In [11]:

d = np.random.randint(1,5,(10,10))

In [12]:
print(d)


[[4 2 1 1 1 2 4 3 4 1]
 [3 4 3 4 1 4 1 2 2 3]
 [3 4 1 1 3 3 2 4 2 1]
 [2 1 1 1 3 4 4 4 2 4]
 [3 3 2 1 4 1 4 1 3 3]
 [1 4 1 3 2 3 4 4 3 1]
 [4 4 2 4 2 2 2 3 4 1]
 [4 2 3 3 4 2 4 3 2 2]
 [3 2 2 4 4 3 4 4 1 4]
 [2 2 3 2 1 3 2 3 1 4]]


In [13]:
d[-1]

array([2, 2, 3, 2, 1, 3, 2, 3, 1, 4])

In [14]:
d[0,0]

4

In [15]:
d[3,5]

4

In [16]:
d[:,0] #all rows of column index 0

array([4, 3, 3, 2, 3, 1, 4, 4, 3, 2])

In [17]:
d[:,-3]


array([3, 2, 4, 4, 1, 4, 3, 3, 4, 3])

In [18]:
d[:5,2] #first five elements of column index 2


array([1, 3, 1, 1, 2])

In [19]:

d[5:,2]  #last 5 elements of column index 2

array([1, 2, 3, 2, 3])

In [20]:
d[:5 ,:5]  # first 5x5 matrix


array([[4, 2, 1, 1, 1],
       [3, 4, 3, 4, 1],
       [3, 4, 1, 1, 3],
       [2, 1, 1, 1, 3],
       [3, 3, 2, 1, 4]])

In [21]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print (x,'\n',y)



[[1 1 1]
 [5 1 3]
 [4 7 7]] 
 [[5 6 7]
 [4 8 5]
 [8 9 8]]


In [22]:
x+y

array([[ 6,  7,  8],
       [ 9,  9,  8],
       [12, 16, 15]])

In [23]:
x-y

array([[-4, -5, -6],
       [ 1, -7, -2],
       [-4, -2, -1]])

In [24]:
x*y


array([[ 5,  6,  7],
       [20,  8, 15],
       [32, 63, 56]])

In [25]:
x/y

array([[0.2       , 0.16666667, 0.14285714],
       [1.25      , 0.125     , 0.6       ],
       [0.5       , 0.77777778, 0.875     ]])

In [26]:
x+10

array([[11, 11, 11],
       [15, 11, 13],
       [14, 17, 17]])

In [27]:
x-10

array([[-9, -9, -9],
       [-5, -9, -7],
       [-6, -3, -3]])

In [28]:
x*10

array([[10, 10, 10],
       [50, 10, 30],
       [40, 70, 70]])

In [29]:
np.dot(x,y)

array([[ 17,  23,  20],
       [ 53,  65,  64],
       [104, 143, 119]])

In [30]:
np.matmul(x,y)

array([[ 17,  23,  20],
       [ 53,  65,  64],
       [104, 143, 119]])

In [31]:
np.multiply(x,y)

array([[ 5,  6,  7],
       [20,  8, 15],
       [32, 63, 56]])

In [32]:
x*y

array([[ 5,  6,  7],
       [20,  8, 15],
       [32, 63, 56]])

In [33]:
np.cross(x,y)



array([[  1,  -2,   1],
       [-19, -13,  36],
       [ -7,  24, -20]])

In [34]:
np.hstack([x,y])

array([[1, 1, 1, 5, 6, 7],
       [5, 1, 3, 4, 8, 5],
       [4, 7, 7, 8, 9, 8]])

In [35]:
np.vstack([x,y])

array([[1, 1, 1],
       [5, 1, 3],
       [4, 7, 7],
       [5, 6, 7],
       [4, 8, 5],
       [8, 9, 8]])

In [36]:
np.append(x,y,axis =0)   #axis 0 is for rowwise and 1 for column wise

array([[1, 1, 1],
       [5, 1, 3],
       [4, 7, 7],
       [5, 6, 7],
       [4, 8, 5],
       [8, 9, 8]])

In [37]:
x.max()

7

In [38]:
x.max(axis = 0)

array([5, 7, 7])

In [39]:
x.min(axis = 1)

array([1, 1, 4])

In [40]:
x.flatten()

array([1, 1, 1, 5, 1, 3, 4, 7, 7])

In [41]:
d[d>3]  # boolean filter


array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4])

In [42]:
d[d==1]   #give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])